### ISSUE TITLE
DMT doesn't work w/compressed MN privkeys

### ISSUE THREAD

**Issue by nmarley** [Bertrand256/dash-masternode-tool#1]

**Comment by Bertrand256** [comment]
DMT doesn't enforce (un)compression of MN privkey that the user provides, but to my knowledge, the Dash network requires that the key is uncompressed. I didn't checked that, but you'll probably get an error message as a result of sending to the network "Start masternode" message using a compressed key.

**Comment by nmarley** [comment]
I am normally able to use compressed keys (starting with `X`) from the Dash-QT client. But yesterday my DMT/Trezor kept giving an error 'til I switched to an uncompressed one.

**Comment by Bertrand256** [comment]
I will investigate it. Can you give me some details: what DMT feature you used (voting or starting masternode) and what was the error message? Thanks.

**Comment by nmarley** [comment]
It is starting the masternode, and the error message I receive is this:

```
Failed to start masternode.

Response from Dash daemon: Masternode broadcast signature verification failed.
```

It only happens using compressed keys. Uncompressed keys beginning with `7` work fine.

**Comment by Bertrand256** [comment]
Thanks @nmarley. I'll look at it after implementing testnet support in the tool.

**Comment by Bertrand256** [comment]
Compressed keys are working now - verified with dashd v12.3 on testnet.
