### ISSUE TITLE
Error when trying to transfer founds from Trezor MN wallet

### ISSUE THREAD

**Issue by elbereth** [Bertrand256/dash-masternode-tool#16]
I am using DMT 0.9.20 under Windows 10 Pro 1803.
Trezor One is at 1.6.2 firmware.
I check server connection and HW connection (both green) :
![image](https://user-images.githubusercontent.com/1632446/43174030-3f274902-8f75-11e8-9d78-d609911c73d1.png)
I then go to Transfer founds from MN, select the transactions and select destination address, when I click Prepare Transaction I get this error message : 
![image](https://user-images.githubusercontent.com/1632446/43174341-c9b9e9de-8f76-11e8-8887-b37fe77af146.png)
And I cannot go further, nothing is prompted on the Trezor key.
This was working with the same setup but firmware 1.6.1.

**Comment by Bertrand256** [comment]
Check if there are no illegal characters in the destination address (eg spaces). In the current version, the dest address is not trimmed, but it will be fixed in the next version. 

If this is not the case, share the contents of the log file (Tools-> Open Log File) here or via email.

**Comment by elbereth** [comment]
That was it. The error message was really not clear.
Maybe this can be improved (and or auto trimming of course).
Thanks !
