### ISSUE TITLE
Frame the message returned by master node as from the master node

### ISSUE THREAD

**Issue by colourful-land** [Bertrand256/dash-masternode-tool#18]
Thanks for the detailed answer of #17 which helped me to address the issue on my node finally.

You said that DashMasterTool has no educational role - that is not to say it should lose clarity.

A Stop sign on the street has no educational role - it does not say that you should stop the car to a complete stop, wait for 3 seconds, see the opposite street clear, then move on. That was left to the driver training courses. A stop sign nevertheless is in big red with the word STOP on it, so an uneducated driver need to STOP to figure out what it means. It didn't, for example, give a big red circle with nothing written on it by reasoning it has no educational intention.

That being said, this issue requests the following:

that the message box of messages returned by a dash node to be framed with a hint that it is returned from the master node, so that people educate themselves by searching the node information or read node source code and not be confused with DashMasterTool own message. This can be done in one a few a few ways. The simplest (not the best) is to explain it with a caption: "node reports". 

A more elaborate way is to display a local computer and a few dots connecting it to a node. The dot represents if the connection is successfully installed, therefore if there is an update message with the connection visually broken it clearly means the update needs to be done on the local side. Then, the message is displayed under the graphical representation of a node, killing the confusing that it might be a local message.

I hope I'm a graphical designer so that I can give a design help, but I would happy to close the issue if you can kindly just add the caption.

**Comment by Bertrand256** [comment]
Thanks for reporting it. I apologize for the lack of reaction for so long - somehow I missed this issue. 

I am currently in the redevelopment of the main window as a consequence of the ongoing Deterministic Masternode List implementation in mainnet. The status displayed by the app after these changes will be based on information from another source (protx list). For now, it's hard to say how it eventually will look like, but I will take your suggestions into account. 

Note that either now and after the changes, the presented status does not show exactly the state of your node at this exact moment but rather how other nodes have seen your masternode some time ago. This means that even after turning off your masternode, the network will see your node as enabled for some time (now it's an hour). DMT has no feature (at least now) to probe the node in a direct way to see what's really going on with it.

**Comment by Bertrand256** [comment]
The main app window has finally been redesigned towards masternode list, so the issue is no longer valid.
