### ISSUE TITLE
Error connecting to Keepkey wallet

### ISSUE THREAD

**Issue by dkaparis** [Bertrand256/dash-masternode-tool#22]
Running under Arch Linux, version v0.9.21 trying to connect to the Keepkey hardware wallet (e.g. by clicking the "Test Hardware Wallet Connection" button) I get an error popup:

```
On linux OS switching between Trezor/Keepkey wallets requires restarting the application.

Please restart the application to continue.
```

Console output:
```
ERROR:root:Exception while connecting hardware wallet
Traceback (most recent call last):
  File "main_dlg.py", line 727, in connect_hardware_wallet
  File "hw_intf.py", line 155, in connect_hw
  File "hw_intf.py", line 38, in control_trezor_keepkey_libs
```
I have not recently switched hw wallet types and using the same configuration, the previous version 0.9.20 connects to the hw wallet without issue.

**Comment by Bertrand256** [comment]
Indeed, a small issue "crept" into the code. I've fixed it and published under the same version. 
Please re-download and verify if it works now.

**Comment by dkaparis** [comment]
Re-downloaded the release and tried again - now Keepkey connects without error.
