### ISSUE TITLE
Error when attempting to save votes to CSV

### ISSUE THREAD

**Issue by taw00** [Bertrand256/dash-masternode-tool#23]
I finished voting and then.... "Save to CSV..." and then this error message:
"save_file_query() missing 1 required positional argument: 'message'"

**Comment by UdjinM6** [comment]
Same here (MacOS 10.14.3)

**Comment by Bertrand256** [comment]
Thanks for reporting. 
Fixed in v0.9.22-hotfix1. The updated binaries are accessible under the old release (v0.9.22).

**Comment by UdjinM6** [comment]
Works for me now! 👍

**Comment by taw00** [comment]
Confirmed. Works.
Linux. Fedora 29. x86_64 -- my own builds of your code.

Closing.
