### ISSUE TITLE
errors when sending unlocked funds from collateralized wallet

### ISSUE THREAD

**Issue by taw00** [Bertrand256/dash-masternode-tool#25]
*Note1: The transaction went through. And a prior transaction on another MN went through with no error.*
*Note2: my setup -- Fedora Linux 29, x86_64. My builds of the code.*

A deadlock was reported. See image 1.
![error-when-sending1](https://user-images.githubusercontent.com/6908872/53362463-42845080-3908-11e9-818e-e79dccb065a8.png)

And underneath that error dialog was another. See image 2.
![error-when-sending2](https://user-images.githubusercontent.com/6908872/53362467-44e6aa80-3908-11e9-893c-552aa28f3009.png)

**Comment by Bertrand256** [comment]
What DMT version?

**Comment by Bertrand256** [comment]
It's probably DMT v0.9.22-beta1 or v0.9.21, right? Both issues should be fixed in v0.9.22.

**Comment by Bertrand256** [comment]
It actually can happen in another case that the one I've fixed. Will look into this.

**Comment by taw00** [comment]
0.9.22-hotfix1 was (is) the version.

**Comment by Bertrand256** [comment]
Closing - fixed in hotfix2.
If it happens again (it shouldn't) please reopen the issue.
