### ISSUE TITLE
Unknown USB interface number: -1

### ISSUE THREAD

**Issue by agulab** [Bertrand256/dash-masternode-tool#26]
I'm getting "Unknown USB interface number: -1" error when trying to communicate with the KeepKey. It doesn't happen with Version 0.9.22 beta 1.
Can I register the ProRegTx masternode using the Beta version?
Thanks

**Comment by Bertrand256** [comment]
Yes, you can use beta1 if works for you.

Can you give me a little more details about the error, specifically: what OS you are using and ideally the log file contents from the place where you see the last occurance of "Unknown USB interface number" error? Thanks.

**Comment by agulab** [comment]
[dmt.log](https://github.com/Bertrand256/dash-masternode-tool/files/2912268/dmt.log)

Of course, here it is. I'm on Windows 10 Home v 1803. I tried restarting the PC and plugging to different USB ports but nothing worked.
I registered successfully using Beta version now.

Thanks for your work!

**Comment by Bertrand256** [comment]
Thanks. 

The reason was the broken (latest) version of the keepkey client library compiled into the DMT executable for Windows. Library downgraded to the latest working version and the resulting DMT binaries published as v0.9.22-hotfix3.

**Comment by Bertrand256** [comment]
Closing. No feedback that the fix does not work.
