### ISSUE TITLE
Encountered invalid prevhash

### ISSUE THREAD

**Issue by agulab** [Bertrand256/dash-masternode-tool#27]
Sorry Bertrand, but I encountered an error trying to transfer funds. After putting the KeepKey pin to Prepare transaction, the error appearing says "(9, 'Encountered invalid prevhash')".
I tried older versions and had the same result (0.9.20.win64 and the new 0.9.22-hotfix3.win64). Also updated my KeepKey firmware just to be sure.

I made the proRegTx some days ago so perhaps it's related to that.

Here is the log with those tries:
[dmt.log](https://github.com/Bertrand256/dash-masternode-tool/files/2920746/dmt.log)

Thanks for your help.

**Comment by agulab** [comment]
And sorry for using KeepKey... it's been a pain in the *** since day one and clearly the worst hardware wallet out there.

**Comment by Bertrand256** [comment]
The reason is the keepkey official API library not being prepared to support inputs with new transaction types (DIP3). I will try to apply a solution designed by Dash devs to path Trezor library, that has similar problem. I hope it will work for Keepkey.

**Comment by Bertrand256** [comment]
Fixed in v0.9.22-hotfix4. 
Please check if it works now.

**Comment by agulab** [comment]
It worked, Bertrand!! Thank you very much for your constant support.

**Comment by Bertrand256** [comment]
Thanks for the confirmation.
