### ISSUE TITLE
Error while withdrawing from MN after Dip3 setup on ledger nano

### ISSUE THREAD

**Issue by statitog** [Bertrand256/dash-masternode-tool#28]
Error on singing tx

An error occurred while sending transation: -26: 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)

**Comment by Bertrand256** [comment]
The reason is - similarly to #27 - the verndor client library (btchip-python) not supporting new Dash transaction types. 
I will check if there is a chance to implement a workaround for this issue.

**Comment by Bertrand256** [comment]
Implemented in v0.9.22-hotifx5.

**Comment by statitog** [comment]
Nice job! Works fine!

**Comment by Bertrand256** [comment]
Great! Thanks for the feedback.
