### ISSUE TITLE
Send error with Keepkey

### ISSUE THREAD

**Issue by babygiraffe05** [Bertrand256/dash-masternode-tool#29]
When sending transactions containing any MN rewards received after ~March 1st, pushing the "Prepare Transaction" button results in the error "(9, 'Encountered invalid prevhash')". HW wallet = Keepkey on latest firmware v5.5. Latest DMT. macOS v10.14.3. Issue was encountered with both remote connections and local hosted Dash wallet 0.13.2.

MN rewards prior to March 1st were unaffected.

**Comment by Bertrand256** [comment]
Please make sure that you have downloaded the latest build (hotfix5). DIP2 transaction support for KeepKey and Ledger was introduced as part of the respective hotfixes for version 0.9.22, so you might have missed it.

**Comment by babygiraffe05** [comment]
I will try that and notify here if it works. It turns out I was on hotfix2, but when I checked for latest updates it returned "You have the latest version of DashMasternode Tool." so I didn't know an update was available.

**Comment by Bertrand256** [comment]
Yes, I know, up until the hotfix5 compilation, the update detection mechanism took into account only the version number (without the hotfix part).

**Comment by babygiraffe05** [comment]
I have updated to hotfix5, with local hosted dashd config including addressindex=1, spentindex=1, timestampindex=1, txindex=1, reindexed running version 0.13.2, and additionally tried connections to suzy.dash-masternode-tool.org:443 without success. I'm still getting the same error message upon attempted transfer of funds.

**Comment by babygiraffe05** [comment]
Nevermind. Problem solved. I had updated the firmware of the Keepkey, but it apparently required multiple updates to get to the latest version, which is v5.10.2, NOT v5.5. This is not my device - was helping a friend - and apparently they had never updated their firmware.

**Comment by Bertrand256** [comment]
Thanks for the information about what solved the issue - it can be helpful for others in a similar situation. 

Btw, that's what I was going to suggest: updating the firmware and removing the transaction cache were the last two things that could help in this situation.
