### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by dotexx** [Bertrand256/dash-masternode-tool#3]
Problems encountered while processing some of the proposals data. Look into the log file for details.

> 2017-11-07 12:43:42 INFO |MainThread |app_config.py |init |App started
> 2017-11-07 12:44:25 ERROR |Dummy-1 |proposals_dlg.py |read_proposals_from_network |Error while processing proposal data. Proposal hash: fab77bf2fbbc1cf8a0eeda7769fc5324011817fe503013a7b131969ec23a2716
> Traceback (most recent call last):
>   File "proposals_dlg.py", line 809, in read_proposals_from_network
> AttributeError: 'int' object has no attribute 'replace'

**Comment by Bertrand256** [comment]
Thank you for the log file. Fix will be released in v0.9.13.

**Comment by Bertrand256** [comment]
Fixed in v0.9.13
