### ISSUE TITLE
"mandatory-script-verify-flag-failed" when sending from ledger wallet

### ISSUE THREAD

**Issue by Steffen-8** [Bertrand256/dash-masternode-tool#30]
I signed a send transaction on a ledger (blue) wallet to transfer excess funds from a masternode address. At the moment where I acknowledge to "Send Transaction" an error message 

> An error occurred while sending transation: -26: 16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)

comes up. I don't get what that means. The same operation had worked before the last Dash software update. Might be a newly introduced incompatibility?

**Comment by Bertrand256** [comment]
Hi. The problem is fixed in v0.9.22-hotfix5 (take a look at #28).
