### ISSUE TITLE
0.9.23 is reporting itself as 0.9.22-hotfix7

### ISSUE THREAD

**Issue by taw00** [Bertrand256/dash-masternode-tool#31]
Setup: Fedora 29 -- 0.9.23 built from source (my RPM)

SSIA -- in the UI it says this is 0.9.22-hotfix7 and asks me to download the latest version. :)

**Comment by Bertrand256** [comment]
My apologies, I forgot that you build binaries using the latest tag and I updated the version number in version.txt after creating a release (tag). I've created a new tag (v0.9.23a) pointing to the latest commit and I hope it solves the problem.

**Comment by taw00** [comment]
Thanks. Fixed! :)
