### ISSUE TITLE
KeepKey not found

### ISSUE THREAD

**Issue by Vladimir7280** [Bertrand256/dash-masternode-tool#32]
Hi! After updating KeepKey to version 6.1.0, I get the message "Cannot find any Keepkey device".
Thanks
P.s. Chrome client works

**Comment by Bertrand256** [comment]
Hi
Support for v6.x Keepkey firmware will be included in the upcoming release, but in the meantime you can test it with this build: https://keybase.pub/bertrand256/dash-masternode-tool/executables/0.9.24-hotfix2/

**Comment by Vladimir7280** [comment]
Thanks! It works! Great job!
