### ISSUE TITLE
No masternodes to vote with

### ISSUE THREAD

**Issue by lordbah** [Bertrand256/dash-masternode-tool#33]
"No masternodes to vote with" when I try to vote. The main screen has found the masternode, status ENABLED, and it has the voting address/key. I can use that voting key to vote on dashcentral.org, so it's valid. v0.9.25-hotfix2. No hardware wallet.

**Comment by Bertrand256** [comment]
For voting on the Dash network, the combination of collateral_tx_hash and collateral_tx_index is used as the masternode id. Most likely, this information is either missing or incorrect in your DMT configuration. 

The best test is to run the following command in the Debug console: 
`masternodelist json collateral_tx_hash-collateral_tx_index`

for example:
`masternodelist json a476f59677f43968ef22c12e250605e42b8ae6d0665fef1354c219ac1e3de82e-0`

**Comment by lordbah** [comment]
It responds with my masternode. All values match the values in DMT.

In DMT, "path" is empty. Is that significant? 

(Sorry this took so long. I received your comment in email and the email implied that I could add to this issue just by replying to the email. That doesn't seem to have worked.)

**Comment by Bertrand256** [comment]
This time I am sorry for the delay - I was on vacation.

I think that now the best approach will be to look at the DMT logs. Can you set "Log level" to "INFO", open & close the proposal window and copy the part of the log file from the following line `INFO | root | MainThread | app_config.py | init | Application started (v 0.9.26-hotfix1)` up to the end of the file and share it with me?

**Comment by lordbah** [comment]
This is the issue?

2019-08-30 07:13:04 WARNING|dmt.proposals|MainThread|proposals_dlg.py|__init__|Voting key for masternode "MN1 (idx:0)" is public and does not allow voting.

I'm going to have to do some reading to understand this.

**Comment by Bertrand256** [comment]
Yes that's the reason. To vote in the app you need to enter private key in the configuration and you have probably entered the public address associated with that key. 

If the private key associated is kept in your Dash Core wallet, to use the DMT voting feature you need to export it in the Debug console using the `dumpprivkey` command or just generate & publish to the blockchain a new voting privkey. For this you can use `Update voting key` from DMT (owner private key will be required) or `protx update_registrar` from Debug console.

**Comment by lordbah** [comment]
Thanks I think that did it, no error. Clicked Edit, clicked "use privkey" next to Owner and Voting, entered the private key, Get Status, success, searched for a Save button next to Cancel, didn't find one, finally saw the Save icon at the top, went to proposals and voted on something.
