### ISSUE TITLE
Customize tool other currencies x11

### ISSUE THREAD

**Issue by elbarros** [Bertrand256/dash-masternode-tool#34]
Is it possible to customize this tool for another currency with x11 clone dash algorithm?

**Comment by Bertrand256** [comment]
The tool can be adapted to coins supported by Trezor/Ledger/Keepkey hardware wallets that have implemented DIP2 and DIP3 improvement proposals (https://github.com/dashpay/dips/blob/master/dip-0003.md). The hash algorithm does not matter.
