### ISSUE TITLE
masternode tool can't recognise my trezor

### ISSUE THREAD

**Issue by fly968** [Bertrand256/dash-masternode-tool#35]
Hi Bertrand256,

I'm a masternode owner. A few days ago I tried to move my reward out from trezor ONE by masternode tool, but masternode tool didn't recognise my trezor. I used masternode tool two or three months ago, there was no problem at that time.  

I tried another trezor one and trezor T, the masternode tool also can't recognise them.  My system is Windows 10. But when I tried masternode tool on my imac the trezors can be recognised. 

Both masternode tool and trezor have been updated. 

Could you help on that? thanks

**Comment by Bertrand256** [comment]
You are most likely affected by one of the Windows updates published several months ago, like in those two cases: https://github.com/spesmilo/electrum/issues/5420 and  https://github.com/trezor/trezord-go/issues/167). 

Try installing the latest Trezor Bridge and if it doesn't help, you should be able to workaround it by starting DMT as Administrator.

If you think it doesn't apply to you, send me the app's log file.

**Comment by fly968** [comment]
Hi Bertrand256,

After trying a few ways to fix this issue finally I give up. Now I'm running MNT perfectly  on macOS system. Thanks for the help anyway!

**Comment by Bertrand256** [comment]
Hi,
Thanks for the feedback. I'm closing this issue now, but feel free to re-open it if you decide to try to make it working on your Windows. In this case I will need access to messages from your DMT log file.

**Comment by fly968** [comment]
Dear Bertrand256,

Hope this email finds you well.

Could you please help me on a following issue when I used Dash masternode tool:

Recently I used Allnotes hosting service to set up a Dash masternode. After setting up the masternode by following Allnotes website instruction, the masternode was enabled.

Next step I did: I would like to use Dash masternode tool to manage this masternode, so I added a new masernode entry in the masternode tool. I created a new " owner private key" and " voting private key " when I enter the data ( the reasons I did that because Allnotes didn't provide the information to me when I registed the masternode with them, also I feel safe when I create private keys by myself) , then re-registered the masternode in masternode tool.

After re-registering masternode, the masternode has be enabled but something wrong. I attached a screenshot for your reference.

Could you please advise what is wrong and how can I fix it? I will really appreciate if you can help me. My computer skill is poor and I don't know anyone else can help on this issue except you. Thank you in advance.

Kind Regards

Hanmin



________________________________

**Comment by Bertrand256** [comment]
Hi Hanmin. 

Unfortunately there is no screenshot attached to your message, so I don't know what the problem really is, nevertheless I would like to point out the most possible cause: in the scenario where you use an external masternode operator, you have probably received the operator's **public** (not private!) key from them, which needs to be entered into DMT configuration accordingly. This is described in this [document](https://github.com/Bertrand256/dash-masternode-tool/blob/master/doc/registering-masternode.md#2-start-the-masternode-registration-wizard-and-fill-in-the-initial-data), section **Operator private key**, third bullet: *"If you employ an external masternode operator who provided you with the operator's public key, then click the use pubkey link and enter that key into the field on the right"*. 

If it doesn't help, I suggest you contact me via Dash Discord, which is a slightly better place to troubleshoot this type of problem (my nickname is the same as the one on Github, but lowercase).

**Comment by fly968** [comment]
Hi Bertrand256,

thanks for your valuable time to reply my email.

I will try to solve the problem by myself first. If it doesn't work, I will meet you in Discord. thanks again for the help!

Have a great week.

Kind regards,
Hanmin


________________________________
