### ISSUE TITLE
Error startup after compile

### ISSUE THREAD

**Issue by dollebrekel** [Bertrand256/dash-masternode-tool#40]
I install win7 did every step. 

When I startup the DMT I get the following error:
Failed to execute script DMT
Error: <NULL>
Traceback: <NULL>

**Comment by Bertrand256** [comment]
1. What's your OS type: Windows 7? And architecture: 64 or 32 bit?
2. Did you compile DMT yourself or using the precompiled binary from GitHub?

**Comment by dollebrekel** [comment]
1. I used Windows 7 64x
2. I compile DMT myself. 

When I compile it in Ubuntu or Arch it works fine. But also wants to get Windows version working.

**Comment by Bertrand256** [comment]
What Python version have you installed on your Windows?

**Comment by dollebrekel** [comment]
For windows, I'm using Phyton3.6.4 86x64

**Comment by Bertrand256** [comment]
I'm guessing that on your Windows libusb dll may be missing.

Do as follows: 
1. Download libusb archive from https://github.com/libusb/libusb/releases/download/v1.0.23/libusb-1.0.23.7z
2. Unpack `libusb-1.0.dll` file from the archive's `MS64\dll` subfolder and copy it to `C:\Windows\System32` or any other directory mentioned in your Windows PATH environment variable.
3. Check if you can execute your compiled DMT binary 

If it doesn't help, execute commands from your `cmd`:
```
cd c:\projects\dash-masternode-tool
c:\projects\virtualenvs\dmt-64\Scripts\activate.bat
python src\dash_masternode_tool.py
```
and post the errors that should appear if there are any problems.

I'm assuming here that paths are the same as described in the DMT 'build' documentation: https://github.com/Bertrand256/dash-masternode-tool/blob/master/doc/build-dmt-windows.md

**Comment by dollebrekel** [comment]
I will reinstall W7 x64 and will follow your suggestions.

Will post my process.
My paths are the same as described.

**Comment by dollebrekel** [comment]
Jup it was the libusb-1.0.dll

**Comment by Bertrand256** [comment]
> Thanks for your help. You can close the issue

You're welcome!
