### ISSUE TITLE
v 0.9.27 produces Segmentation fault while v 0.9.26-hotfix4 runs just fine in the latest Manjaro KDE(21.0.5).

### ISSUE THREAD

**Issue by pcrypt** [Bertrand256/dash-masternode-tool#42]
INFO:root:===========================================================================
INFO:root:Application started (v 0.9.27)
INFO:root:Environment:
INFO:root:environ({'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/manjaro-amd:@/tmp/.ICE-unix/10413,unix/manjaro-amd:/tmp/.ICE-unix/10413', 'WINDOWID': '4194311', 'COLORTERM': 'truecolor', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session1', 'LANGUAGE': '', 'LC_ADDRESS': 'el_GR.UTF-8', 'LC_NAME': 'el_GR.UTF-8', 'SHELL_SESSION_ID': 'c78e6fe5b8f040879edc818f253acc92', 'DESKTOP_SESSION': 'plasma', 'LC_MONETARY': 'el_GR.UTF-8', 'GTK_RC_FILES': '/etc/gtk/gtkrc:/home/ubuntu/.gtkrc:/home/ubuntu/.config/gtkrc', 'XCURSOR_SIZE': '24', 'EDITOR': '/usr/bin/nano', 'GTK_MODULES': 'canberra-gtk-module', 'XDG_SEAT': 'seat0', 'PWD': '/home/ubuntu/CryptoClients', 'XDG_SESSION_DESKTOP': 'KDE', 'LOGNAME': 'ubuntu', 'XDG_SESSION_TYPE': 'x11', 'XAUTHORITY': '/home/ubuntu/.Xauthority', 'MOTD_SHOWN': 'pam', 'GTK2_RC_FILES': '/etc/gtk-2.0/gtkrc:/home/ubuntu/.gtkrc-2.0:/home/ubuntu/.config/gtkrc-2.0', 'HOME': '/home/ubuntu', 'LC_PAPER': 'el_GR.UTF-8', 'LANG': 'en_US.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.pdf=00;32:*.ps=00;32:*.txt=00;32:*.patch=00;32:*.diff=00;32:*.log=00;32:*.tex=00;32:*.doc=00;32:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'KDE', 'KONSOLE_DBUS_SERVICE': ':1.142', 'KONSOLE_DBUS_SESSION': '/Sessions/1', 'PROFILEHOME': '', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'KONSOLE_VERSION': '210400', 'KDE_SESSION_UID': '1000', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LC_IDENTIFICATION': 'el_GR.UTF-8', 'USER': 'ubuntu', 'COLORFGBG': '15;0', 'KDE_SESSION_VERSION': '5', 'PAM_KWALLET5_LOGIN': '/run/user/1000/kwallet5.socket', 'DISPLAY': ':0', 'SHLVL': '1', 'LC_TELEPHONE': 'el_GR.UTF-8', 'LC_MEASUREMENT': 'el_GR.UTF-8', 'XDG_VTNR': '1', 'XDG_SESSION_ID': '2', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'XDG_RUNTIME_DIR': '/run/user/1000', 'LC_TIME': 'el_GR.UTF-8', 'QT_AUTO_SCREEN_SCALE_FACTOR': '0', 'XCURSOR_THEME': 'breeze_cursors', 'GTK3_MODULES': 'xapp-gtk3-module', 'XDG_DATA_DIRS': '/home/ubuntu/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'KDE_FULL_SESSION': 'true', 'BROWSER': '/usr/bin/firefox', 'PATH': '/tmp/_MEI9UVrik:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'KDE_APPLICATIONS_AS_SCOPE': '1', 'MAIL': '/var/spool/mail/ubuntu', 'LC_NUMERIC': 'el_GR.UTF-8', 'KONSOLE_DBUS_WINDOW': '/Windows/1', '_': './DashMasternodeTool', 'OLDPWD': '/home/ubuntu/Desktop', 'LD_LIBRARY_PATH': '/tmp/_MEI9UVrik', 'QT_PLUGIN_PATH': '/tmp/_MEI9UVrik/PyQt5/Qt/plugins', 'QML2_IMPORT_PATH': '/tmp/_MEI9UVrik/PyQt5/Qt/qml', 'SSL_CERT_FILE': '/tmp/_MEI9UVrik/certifi/cacert.pem'})
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: FcPattern object weight does not accept value [40 210)
Segmentation fault (core dumped)

**Comment by Bertrand256** [comment]
I did another build for v0.9.27 with some tweaks in the included libraries to make it working with Ubuntu 16.04 and according to my tests it works with the latest Majnaro as well. It has been published under the same revision as before: https://github.com/Bertrand256/dash-masternode-tool/releases/tag/v0.9.27

**Comment by pcrypt** [comment]
tested and works OK
Thanx
