### ISSUE TITLE
Can't transfer funds from wallet, name 'fg_color' is not defined

### ISSUE THREAD

**Issue by frosted97** [Bertrand256/dash-masternode-tool#43]
After I approve the signature on my Trezor One, I get an error that says "name 'fg_color' is not defined" and then the screen just closes. Nothing is sent.

**Comment by frosted97** [comment]
This is version 0.9.28. I tried multiple times shutting down the app and re-starting but get the same error.

**Comment by Bertrand256** [comment]
Thanks for reporting it. 
The issues is fixed in version 0.9.29 (https://github.com/Bertrand256/dash-masternode-tool/releases/tag/v0.9.29).

**Comment by frosted97** [comment]
Thanks for the fix! I can confirm that this is not an issue in the latest release, v0.9.29.
