### ISSUE TITLE
Duplicating digits when entering Trezor pin (Windows 10)

### ISSUE THREAD

**Issue by scott-herring** [Bertrand256/dash-masternode-tool#44]
We were setting up a node today and got stuck entering the Trezor pin. Each character appeared to double up, and then we got an error about pin being too long on submit.

**Comment by Bertrand256** [comment]
Hi, I have a few questions:
1. Can it be reproduced or did it only happen once?
2. What is your OS?
3. Which Trezor model is involved with the issue: One or T
