### ISSUE TITLE
bug when registering MN

### ISSUE THREAD

**Issue by vampyren** [Bertrand256/dash-masternode-tool#52]
During registration wizzard it seems the address for funding doos not get copied to the message. See image:

![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/276ace70-1d6d-4aba-92c7-b7d86a7c91e6)

**Comment by Bertrand256** [comment]
Ooops, thanks for reporting this.

**Comment by Bertrand256** [comment]
Fixed in v0.9.35-rc1: https://github.com/Bertrand256/dash-masternode-tool/releases/tag/v0.9.35-rc1

**Comment by vampyren** [comment]
Awesome! I tested it and it works! Thank you for fixing this.

**Comment by Bertrand256** [comment]
The fix has been published in the official (not RC) release: v0.9.35. 
I'm closing the issue, but feel free do reopen it if needed.
