### ISSUE TITLE
Saving MN information takes minutes....

### ISSUE THREAD

**Issue by vampyren** [Bertrand256/dash-masternode-tool#56]
For some reason when trying to save to a file  takes some minute and locks all windows. Why is that? this is a simple operation and should not at the very least lock all windows (even outside of DMT!)

![locked window](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/c0ec842f-3667-4e68-918f-39cb0030db8b)

**Comment by Bertrand256** [comment]
Fixed in [v0.9.36-rc2](https://github.com/Bertrand256/dash-masternode-tool/releases/tag/v0.9.36-rc2)

This was due to a bug in the Qt library occurring only on the Windows operating system under specific conditions.

**Comment by Bertrand256** [comment]
I'm assuming this issue is resolved just like #55. If not, feel free to reopen the issue.
