### ISSUE TITLE
Wrong MN Type

### ISSUE THREAD

**Issue by gades** [Bertrand256/dash-masternode-tool#62]
<img width="1187" alt="Screenshot 2023-09-03 at 08 40 00" src="https://github.com/Bertrand256/dash-masternode-tool/assets/4200730/94b99783-25bf-43ff-bc1a-e3dfeca51a70">

Here is part from masternode list

`
    
     dash-cli masternode list | grep -A 3  65.109.95.133

    "address": "65.109.95.133:9999",

    "payee": "XnB91jHVC45PZT6zBMeawcPB8Zaiiu4PDz",

    "status": "ENABLED",

    "type": "Regular",
`

looks like the issue was appear because where I did create MN did check type between Performance and Regular and I'm seeing in the config for 65.109.95.133
platform_p2p_port = 26656
platform_http_port = 443

**Comment by Bertrand256** [comment]
Can you explain more about what the problem is? If I understand correctly, it involves a masternode with IP address 65.109.95.133, but to me, the information shown by DMT and by the network is consistent, so what's the problem?

**Comment by gades** [comment]
1) The application is showing type HighPerformance instead of regular (you can check it by execute dash-cli masternode list | grep -A 3  65.109.95.133)
2) Another issue , when you create new node please switch type to HighPerformance and back to regular. After in the config will be filled platform_p2p_port  and platform_http_port

Looks like after enabling node type was wrong on public dash node and it's return HighPerformance instead of regular

**Comment by Bertrand256** [comment]
> 1. The application is showing type HighPerformance instead of regular (you can check it by execute dash-cli masternode list | grep -A 3  65.109.95.133)

Are you sure you mean the information shown on the "Masternodes (network)" tab? 
DMT shows the Regular type on it, not HighPerformance: 
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/9880025/287cc0c2-4771-461a-a220-58703d1f7803)
Actually, in your screenshot it is exactly the same: masternode 65.109.95.133 has the Regular type. HighPerf is shown for a completely different masternode: 65.109.239.193.

> 2\. Another issue , when you create new node please switch type to HighPerformance and back to regular. After in the config will be filled platform_p2p_port  and platform_http_port

I assume that here you mean the parameters in the config file, not the visual controls in the user interface. If so, this is done on purpose, for preserving values, in case the user switches between Regular and HighPerformance mode. When your masternode is set as Regular, the values from config file are not taken into account and UI components for platform http/p2p port are not shown.

**Comment by gades** [comment]
yes, it's my mistake
