### ISSUE TITLE
Does not work correctly with Dash Core version v21.1.0

### ISSUE THREAD

**Issue by jTd7bPLFb** [Bertrand256/dash-masternode-tool#67]
Transactions are not displayed.
Addresses look like empty, although they are not.

**Comment by mrssv** [comment]
Confirming it. Same issues.

**Comment by Bertrand256** [comment]
Confirming the problem. v21 introduces changes in API data format for transaction information, which affects the functionality of the wallet. A fix is on the way.

**Comment by Bertrand256** [comment]
The issues are resolved in v0.9.39 (https://github.com/Bertrand256/dash-masternode-tool/releases/tag/v0.9.39).
